//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsPresentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionCommand
    {
        public int Id { get; set; }
        public int BotActionId { get; set; }
        public int ControllerCommandId { get; set; }
        public int ControllerLayoutId { get; set; }
    
        public virtual BotAction BotAction { get; set; }
        public virtual ControllerCommand ControllerCommand { get; set; }
        public virtual ControllerLayout ControllerLayout { get; set; }
    }
}
