//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsPresentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotAction
    {
        public BotAction()
        {
            this.ActionCommands = new HashSet<ActionCommand>();
            this.BotActionSerialCommands = new HashSet<BotActionSerialCommand>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<ActionCommand> ActionCommands { get; set; }
        public virtual ICollection<BotActionSerialCommand> BotActionSerialCommands { get; set; }
    }
}
