//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsPresentation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BotInteractionContainer : DbContext
    {
        public BotInteractionContainer()
            : base("name=BotInteractionContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BotAction> BotActions { get; set; }
        public DbSet<ControllerCommand> ControllerCommands { get; set; }
        public DbSet<ControllerLayout> ControllerLayouts { get; set; }
        public DbSet<ActionCommand> ActionCommands { get; set; }
        public DbSet<SerialCommand> SerialCommands { get; set; }
        public DbSet<BotActionSerialCommand> BotActionSerialCommands { get; set; }
    }
}
